// Ported from HedgeEmEnumerations.cs (hedgeem_client_class_library)

export enum BettingStage {
  NON_BETTING = -1,
  HOLE = 0,
  FLOP = 1,
  TURN = 2,
}

export enum GameState {
  UNCHANGED = 'UNCHANGED',
  INVALID_CARD = 'INVALID_CARD',
  CARD_ALREADY_DEALT = 'CARD_ALREADY_DEALT',
  STATUS_SETUP = 'STATUS_SETUP',
  STATUS_START = 'STATUS_START',
  STATUS_MANUAL_DEALING_HOLE = 'STATUS_MANUAL_DEALING_HOLE',
  STATUS_HOLE = 'STATUS_HOLE',
  STATUS_FLOP_CARD1 = 'STATUS_FLOP_CARD1',
  STATUS_FLOP_CARD2 = 'STATUS_FLOP_CARD2',
  STATUS_FLOP_CARD3 = 'STATUS_FLOP_CARD3',
  STATUS_FLOP = 'STATUS_FLOP',
  STATUS_TURN = 'STATUS_TURN',
  STATUS_RIVER = 'STATUS_RIVER',
}

export enum HandStatus {
  UNDEFINED = 'UNDEFINED',
  IN_NON_BETTING_STAGE = 'IN_NON_BETTING_STAGE',
  IN_PLAY_PREVIOUS_BETTING_STAGE_NOT_ACTIVE = 'IN_PLAY_PREVIOUS_BETTING_STAGE_NOT_ACTIVE',
  IN_PLAY_BETTING_STAGE_ACTIVE = 'IN_PLAY_BETTING_STAGE_ACTIVE',
  IN_PLAY_DISABLED = 'IN_PLAY_DISABLED',
  IN_PLAY_DEAD = 'IN_PLAY_DEAD',
  IN_PLAY_FAVOURITE = 'IN_PLAY_FAVOURITE',
  IN_PLAY_WILL_WIN = 'IN_PLAY_WILL_WIN',
  IN_PLAY_WINNER = 'IN_PLAY_WINNER',
}

export enum TableType {
  PERSONAL = 1,
  COMMUNAL = 2,
  TEST_HARNESS = 3,
  ANONYMOUS = 4,
}

export enum AuthMethod {
  OTHER = 1,
  HEDGEEM_ACCOUNT = 2,
  FACEBOOK = 3,
  TWITTER = 4,
  GOOGLE_PLUS = 5,
  APPLE_GUID = 6,
  ANON_USER = 7,
}

export enum UserRole {
  UNSPECIFIED_DUE_TO_ERROR = 'UNSPECIFIED_DUE_TO_ERROR',
  BASIC_USER = 'BASIC_USER',
  PAYING_USER = 'PAYING_USER',
  ANON_USER = 'ANON_USER',
  ADMIN = 'ADMIN',
}

export enum AcknowledgementType {
  ACK = 'ACK',
  NACK = 'NACK',
  UNKNOWN = 'UNKNOWN',
}
