// Ported from hedgeem_client_class_library (HedgeEmGameState, HedgeEmSeat, HedgeEmBet, HedgeEmPlayer)
import { BettingStage, GameState, HandStatus, UserRole } from './enums';

export interface HedgeEmSeat {
  seatId: number;
  playerId: string;         // UUID (Supabase auth.users.id)
  playerName: string;
  seatBalance: number;
  avatarImageUrl: string;
}

export interface HedgeEmBet {
  playerId: string;
  bettingStage: BettingStage;
  seatIndex: number;
  handIndex: number;        // 0-3
  betAmount: number;
  recordedOdds: number;
}

// Per-hand, per-stage odds panel — equivalent to the betting panel data in DotNetHedgeEmClient
export interface HedgeEmHandOdds {
  handIndex: number;        // 0-3
  bettingStage: BettingStage;
  handStatus: HandStatus;
  winPercentage: number;
  drawPercentage: number;
  odds: number;             // e.g. 4.5 → displayed as "1:4.5"
}

export interface HedgeEmGameState {
  tableId: number;
  gameId: string;
  gameState: GameState;
  bettingStage: BettingStage;
  numberOfHands: number;
  numberOfSeats: number;
  jackpotValue: number;
  hands: string[];          // e.g. ["AcKd", "QsJs", "8h7c", "5d2c"] — null before STATUS_HOLE
  flopCard1: string | null;
  flopCard2: string | null;
  flopCard3: string | null;
  turnCard: string | null;
  riverCard: string | null;
  seats: HedgeEmSeat[];
  bets: HedgeEmBet[];
  handOdds: HedgeEmHandOdds[];
}

export interface HedgeEmPlayer {
  playerId: string;         // UUID (Supabase auth.users.id)
  username: string;
  displayName: string;
  accountBalance: number;
  avatarImageUrl: string;
  role: UserRole;
  isActive: boolean;
  personalTableId: number | null;
}

// Request / response shapes for REST endpoints

export interface PlaceBetRequest {
  playerId: string;
  seatIndex: number;
  handIndex: number;        // 0-3
  betAmount: number;
}

export interface PlaceBetResponse {
  acknowledgement: 'ACK' | 'NACK';
  message: string;
  updatedSeatBalance: number;
}

export interface TopUpRequest {
  playerId: string;
  amount: number;
}

export interface TopUpResponse {
  acknowledgement: 'ACK' | 'NACK';
  newSeatBalance: number;
  newAccountBalance: number;
}

export interface SitRequest {
  playerId: string;
  buyInAmount: number;
}

export interface SitResponse {
  acknowledgement: 'ACK' | 'NACK';
  seatId: number;
  seatBalance: number;
}

export interface ApiError {
  error: string;
}

// ============================================================
// BULK GAME DATA — GET /api/games/bulk
//
// Ported from HedgeEmGameState + HedgeEmHandStageInfo (hedgeem_client_class_library).
// Maps the C# DataContract serialisation to a clean REST JSON schema.
//
// The JS client's static coreData[] and three_handed_game_data[] arrays contain
// objects of this shape — generated by calling the legacy f_get_bulk_gamestate_list
// SOAP endpoint. This schema is the REST equivalent.
//
// Field naming convention: camelCase here, matching existing REST API style.
// The JS client coredata.js uses snake_case (bc1, hand_stage_info_list etc) —
// HEDGE-122 handles the mapping when regenerating the offline datasets.
// ============================================================

/**
 * Per-hand, per-stage odds and status data.
 * Equivalent to C# HedgeEmHandStageInfo (DataContract).
 *
 * One entry exists for each combination of hand and stage.
 * For a 3-handed game with 4 stages: 3 × 4 = 12 entries in handStageInfoList.
 * Ordered: all hands for HOLE, then all hands for FLOP, TURN, RIVER.
 */
export interface BulkHandStageInfo {
  handIndex: number;           // 0-based (0 to numberOfHands-1)
  bettingStage: BettingStage;  // HOLE | FLOP | TURN | RIVER

  // Win/draw probabilities — all values 0–100 (percentage)
  percentWin: number;
  percentDraw: number;
  percentWinOrDraw: number;

  // Odds chain: actual → margin (house edge applied) → rounded (for display)
  // e.g. 50% win → oddsActual=2.0, oddsMargin=1.94 (3% house), oddsRounded=1.9
  oddsActual: number;
  oddsMargin: number;
  oddsRounded: number;         // Displayed to player as "1:X"

  // RTP diagnostics — used to validate house margin settings
  actualRtp: number;           // oddsRounded / oddsActual (ideal = targetRtp)
  roundingRake: number;        // (oddsMargin - oddsRounded) / oddsActual

  // Hand status flags
  statusIsWinner: boolean;     // true at RIVER if this hand wins
  statusCantLose: boolean;     // true if hand cannot be beaten at this stage
  statusIsFavourite: boolean;  // true if this hand has the highest win%
  statusBestRtp: boolean;      // true if this hand offers best value (lowest house margin)

  // Best 5-card hand — populated at FLOP onwards (null at HOLE stage)
  bestFiveCards: string | null; // e.g. "Ac Kd Qh Js Tc"

  // Human-readable hand description — populated at FLOP onwards
  handDescShort: string | null; // e.g. "Two Pair"
  handDescLong: string | null;  // e.g. "Two Pair, Aces and Kings"
}

/**
 * A single fully pre-generated game — all cards dealt, all stage odds calculated.
 * Equivalent to C# HedgeEmGameState (DataContract), minus session/table/bet fields
 * which are not relevant to pre-generated bulk data.
 *
 * The JS client coredata.js equivalent field names are shown in comments.
 */
export interface BulkGameState {
  gameId: string;              // Unique game identifier (coredata: not present in JS arrays)
  numberOfHands: number;       // 3 or 4 (coredata: number_of_hands)
  numberOfBettingStages: number; // Always 3 (HOLE, FLOP, TURN); RIVER is reveal-only

  // Hole cards — one 4-char string per hand e.g. "AcKd" (coredata: hands[])
  hands: string[];

  // Board cards (coredata: bc1–bc5)
  bc1: string;                 // Flop card 1
  bc2: string;                 // Flop card 2
  bc3: string;                 // Flop card 3
  bc4: string;                 // Turn card
  bc5: string;                 // River card

  // Flat list of per-hand per-stage data, length = numberOfHands × 4 stages
  // Ordered by stage then hand: HOLE[0..n], FLOP[0..n], TURN[0..n], RIVER[0..n]
  // (coredata: hand_stage_info_list[])
  handStageInfoList: BulkHandStageInfo[];
}

/** Request body for POST /api/games/bulk */
export interface BulkGamesRequest {
  numberOfGames: number;       // How many games to generate (1–200)
  numberOfHands?: number;      // 3 or 4 (default: 3, matching three_handed_game_data)
  targetRtp?: number;          // House RTP target e.g. 0.97 (default: 0.97)
}

/** Response body for POST /api/games/bulk */
export interface BulkGamesResponse {
  games: BulkGameState[];
  numberOfGames: number;       // Actual count returned (may be < requested if capped)
  numberOfHands: number;
  targetRtp: number;
  generatedAt: string;         // ISO 8601 timestamp
}
