/**
 * POST /api/games/bulk
 *
 * Generates N complete pre-calculated game states — each with all 4 stages
 * (HOLE, FLOP, TURN, RIVER) of odds already computed.
 *
 * This is the REST equivalent of the legacy C# SOAP method f_get_bulk_gamestate_list
 * (hedgeem_asp_webservice/App_Code/IService1.cs:643). The JS client's static
 * coreData[] and three_handed_game_data[] arrays in coredata.js were originally
 * generated by that SOAP endpoint — this endpoint replaces it.
 *
 * Pipeline per game (mirrors HedgeEmTable.f_shuffle_deal_and_calculate_odds):
 *   1. Shuffle deck + deal hole cards + board cards  (dealGame)
 *   2. Calculate pre-flop odds                       (calculatePreFlopOdds)
 *   3. Calculate flop odds                           (calculateFlopOdds)
 *   4. Calculate turn odds                           (calculateTurnOdds)
 *   5. Deterministic river evaluation                (calculateRiverOdds)
 *   6. Apply house margin chain to each stage        (computeOddsChain)
 *   7. Determine status flags (winner, favourite, cant-lose, best-rtp)
 *   8. Populate best-five-cards and hand descriptions at flop onwards
 *
 * Request body (BulkGamesRequest):
 *   numberOfGames  — how many games to generate (1–200, default 50)
 *   numberOfHands  — 3 or 4 (default 3, matching three_handed_game_data)
 *   targetRtp      — house RTP e.g. 0.97 (default 0.97)
 *
 * Response (BulkGamesResponse):
 *   games[]        — array of BulkGameState objects
 *   numberOfGames  — actual count returned
 *   numberOfHands
 *   targetRtp
 *   generatedAt    — ISO timestamp
 *
 * HEDGE-121 — implement pre-generated game queue + GET /api/games/bulk endpoint
 */
import { VercelRequest, VercelResponse } from '@vercel/node';
import { applyCors, handleOptions } from '../_lib/cors';
import { authenticate } from '../_lib/auth';
import { BettingStage, HandStatus } from '../_lib/enums';
import {
  BulkGameState,
  BulkGamesRequest,
  BulkGamesResponse,
  BulkHandStageInfo,
} from '../_lib/types';
import {
  dealGame,
  calculatePreFlopOdds,
  calculateFlopOdds,
  calculateTurnOdds,
  calculateRiverOdds,
  computeOddsChain,
  getBestFiveCards,
  getHandDescriptionShort,
  getHandDescriptionLong,
  HandOddsResult,
} from '../_lib/utils';

const MIN_GAMES   = 1;
const MAX_GAMES   = 200;
const DEFAULT_GAMES = 50;
const DEFAULT_HANDS = 3;
const DEFAULT_RTP   = 0.97;

// ============================================================
// STAGE BUILDER
// Converts raw Monte Carlo results into BulkHandStageInfo entries,
// applying the house margin chain and computing all status flags.
// ============================================================

function buildStageEntries(
  hands: string[],
  community: string[],       // All community cards revealed so far (0–5)
  stage: BettingStage,
  oddsResults: HandOddsResult[],
  targetRtp: number,
): BulkHandStageInfo[] {
  const n = hands.length;

  // Precompute odds chains for all hands
  const chains = oddsResults.map(r => computeOddsChain(r.winPercentage, r.drawPercentage, targetRtp));

  // Identify special hands
  let favouriteIdx = -1;
  let highestWin   = -1;
  let bestRtpIdx   = -1;
  let highestOdds  = -1;

  for (let i = 0; i < n; i++) {
    if (oddsResults[i].winPercentage > highestWin) {
      highestWin = oddsResults[i].winPercentage;
      favouriteIdx = i;
    }
    if (chains[i].oddsRounded > highestOdds) {
      highestOdds = chains[i].oddsRounded;
      bestRtpIdx = i;
    }
  }

  // At RIVER, the winner is whoever has winPercentage=100 (or drawPercentage=100 for tie)
  const riverWinners = stage === BettingStage.RIVER
    ? oddsResults.map(r => r.winPercentage === 100 || r.drawPercentage === 100)
    : null;

  return hands.map((hand, i) => {
    const r = oddsResults[i];
    const c = chains[i];

    // cant-lose: this hand cannot be beaten — win+draw = 100%
    const statusCantLose = (r.winPercentage + r.drawPercentage) >= 99.9;

    // best-five and descriptions available once 5+ cards are known (flop onwards)
    const totalCards = 2 + community.length; // hole + community
    const allCards = [hand.slice(0, 2), hand.slice(2, 4), ...community];
    const hasEnoughForEval = totalCards >= 5;

    return {
      handIndex: i,
      bettingStage: stage,

      percentWin: r.winPercentage,
      percentDraw: r.drawPercentage,
      percentWinOrDraw: parseFloat((r.winPercentage + r.drawPercentage).toFixed(1)),

      oddsActual:   c.oddsActual,
      oddsMargin:   c.oddsMargin,
      oddsRounded:  c.oddsRounded,
      actualRtp:    c.actualRtp,
      roundingRake: c.roundingRake,

      statusIsWinner:   riverWinners ? riverWinners[i] : false,
      statusCantLose,
      statusIsFavourite: i === favouriteIdx,
      statusBestRtp:     i === bestRtpIdx,

      bestFiveCards:  hasEnoughForEval ? getBestFiveCards(allCards).join(' ') : null,
      handDescShort:  hasEnoughForEval ? getHandDescriptionShort(allCards) : null,
      handDescLong:   hasEnoughForEval ? getHandDescriptionLong(allCards) : null,
    };
  });
}

// ============================================================
// GAME GENERATOR
// Produces one fully pre-calculated BulkGameState.
// Mirrors HedgeEmTable.f_shuffle_deal_and_calculate_odds().
// ============================================================

function generateGame(gameIndex: number, numberOfHands: number, targetRtp: number): BulkGameState {
  const dealt = dealGame(numberOfHands);
  const { hands, bc1, bc2, bc3, bc4, bc5 } = dealt;
  const flop = [bc1, bc2, bc3];

  // Calculate odds at each stage via Monte Carlo (river is deterministic)
  const holeOdds  = calculatePreFlopOdds(hands);
  const flopOdds  = calculateFlopOdds(hands, flop);
  const turnOdds  = calculateTurnOdds(hands, flop, bc4);
  const riverOdds = calculateRiverOdds(hands, [bc1, bc2, bc3, bc4, bc5]);

  // Build hand_stage_info_list: ordered by stage then hand
  // (matches the C# hand_stage_info_list ordering used by dealStatus * numberOfHands + hand)
  const handStageInfoList: BulkHandStageInfo[] = [
    ...buildStageEntries(hands, [],                     BettingStage.HOLE,  holeOdds,  targetRtp),
    ...buildStageEntries(hands, flop,                   BettingStage.FLOP,  flopOdds,  targetRtp),
    ...buildStageEntries(hands, [...flop, bc4],         BettingStage.TURN,  turnOdds,  targetRtp),
    ...buildStageEntries(hands, [bc1, bc2, bc3, bc4, bc5], BettingStage.RIVER, riverOdds, targetRtp),
  ];

  return {
    gameId: `BULK-${String(gameIndex + 1).padStart(4, '0')}`,
    numberOfHands,
    numberOfBettingStages: 3,   // HOLE, FLOP, TURN (RIVER is reveal-only, no betting)
    hands,
    bc1, bc2, bc3, bc4, bc5,
    handStageInfoList,
  };
}

// ============================================================
// HANDLER
// ============================================================

export default function handler(req: VercelRequest, res: VercelResponse): void {
  applyCors(res);
  if (handleOptions(req, res)) return;

  if (req.method !== 'POST') {
    res.status(405).json({ error: 'Method not allowed.' });
    return;
  }

  const auth = authenticate(req, res);
  if (!auth) return;

  const body: BulkGamesRequest = req.body ?? {};
  const numberOfGames = body.numberOfGames ?? DEFAULT_GAMES;
  const numberOfHands = body.numberOfHands ?? DEFAULT_HANDS;
  const targetRtp     = body.targetRtp     ?? DEFAULT_RTP;

  if (
    typeof numberOfGames !== 'number' || !Number.isInteger(numberOfGames) ||
    numberOfGames < MIN_GAMES || numberOfGames > MAX_GAMES
  ) {
    res.status(400).json({ error: `numberOfGames must be an integer between ${MIN_GAMES} and ${MAX_GAMES}.` });
    return;
  }

  if (numberOfHands !== 3 && numberOfHands !== 4) {
    res.status(400).json({ error: 'numberOfHands must be 3 or 4.' });
    return;
  }

  if (typeof targetRtp !== 'number' || targetRtp <= 0 || targetRtp >= 1) {
    res.status(400).json({ error: 'targetRtp must be a number between 0 and 1 exclusive (e.g. 0.97).' });
    return;
  }

  const games: BulkGameState[] = [];
  for (let i = 0; i < numberOfGames; i++) {
    games.push(generateGame(i, numberOfHands, targetRtp));
  }

  const response: BulkGamesResponse = {
    games,
    numberOfGames: games.length,
    numberOfHands,
    targetRtp,
    generatedAt: new Date().toISOString(),
  };

  res.status(200).json(response);
}
